#!/usr/bin/env python3
"""Export metric definitions, screen bindings, latest snapshots, settings,
and workspace grants to a SQL backup file.

Produces db/metrics_backup.sql with idempotent INSERT OR REPLACE statements.
Run manually or automatically via the pre-commit git hook.
"""

import sqlite3
import os
import sys

DB_PATH = os.path.expanduser("~/Library/Application Support/com.kiingo.localcli/state.sqlite")
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_PATH = os.path.join(REPO_ROOT, "db", "metrics_backup.sql")


def quote(value):
    """SQL-escape a value."""
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    # Escape single quotes
    return "'" + str(value).replace("'", "''") + "'"


def export_rows(conn, table, query, columns):
    """Generate INSERT OR REPLACE statements for query results."""
    lines = []
    cursor = conn.execute(query)
    rows = cursor.fetchall()
    for row in rows:
        vals = ", ".join(quote(v) for v in row)
        cols = ", ".join(columns)
        lines.append(f"INSERT OR REPLACE INTO {table} ({cols}) VALUES ({vals});")
    return lines


def main():
    if not os.path.exists(DB_PATH):
        print(f"Database not found at {DB_PATH}, skipping export", file=sys.stderr)
        sys.exit(0)

    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA busy_timeout = 5000")

    output_lines = [
        "-- Kiingo Command Center: Metrics DB Backup",
        "-- Auto-generated by scripts/export_metrics_db.py",
        "-- Re-run or let the pre-commit hook regenerate this file.",
        "",
        "-- ============================================",
        "-- Metric Definitions",
        "-- ============================================",
        "",
    ]

    # --- metric_definitions ---
    md_cols = [
        "id", "name", "slug", "instructions", "template_html",
        "ttl_seconds", "provider", "model", "profile_id",
        "enabled", "proactive", "metadata_json", "created_at", "updated_at",
    ]
    md_query = f"SELECT {', '.join(md_cols)} FROM metric_definitions ORDER BY slug"
    output_lines += export_rows(conn, "metric_definitions", md_query, md_cols)

    output_lines += [
        "",
        "-- ============================================",
        "-- Screen-Metric Bindings",
        "-- ============================================",
        "",
    ]

    # --- screen_metrics ---
    sm_cols = [
        "id", "screen_id", "metric_id", "position", "layout_hint",
        "grid_x", "grid_y", "grid_w", "grid_h",
    ]
    sm_query = f"SELECT {', '.join(sm_cols)} FROM screen_metrics ORDER BY screen_id, position"
    output_lines += export_rows(conn, "screen_metrics", sm_query, sm_cols)

    output_lines += [
        "",
        "-- ============================================",
        "-- Latest Snapshot per Metric (completed only)",
        "-- ============================================",
        "",
    ]

    # --- metric_snapshots (latest completed per metric) ---
    snap_cols = [
        "id", "metric_id", "values_json", "rendered_html",
        "status", "created_at", "completed_at",
    ]
    snap_query = f"""
        SELECT {', '.join(snap_cols)}
        FROM metric_snapshots s
        WHERE s.status = 'completed'
          AND s.created_at = (
            SELECT MAX(s2.created_at)
            FROM metric_snapshots s2
            WHERE s2.metric_id = s.metric_id AND s2.status = 'completed'
          )
        ORDER BY s.metric_id
    """
    output_lines += export_rows(conn, "metric_snapshots", snap_query, snap_cols)

    output_lines += [
        "",
        "-- ============================================",
        "-- Settings (app config, nav order, migrations)",
        "-- ============================================",
        "",
    ]

    # --- settings ---
    st_cols = ["key", "value_json", "updated_at"]
    st_query = f"SELECT {', '.join(st_cols)} FROM settings ORDER BY key"
    output_lines += export_rows(conn, "settings", st_query, st_cols)

    output_lines += [
        "",
        "-- ============================================",
        "-- Workspace Grants",
        "-- ============================================",
        "",
    ]

    # --- workspace_grants ---
    wg_cols = ["id", "path", "granted_by", "granted_at", "revoked_at"]
    wg_query = f"SELECT {', '.join(wg_cols)} FROM workspace_grants ORDER BY granted_at"
    output_lines += export_rows(conn, "workspace_grants", wg_query, wg_cols)

    output_lines.append("")

    conn.close()

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        f.write("\n".join(output_lines))

    count_defs = sum(1 for l in output_lines if l.startswith("INSERT") and "metric_definitions" in l)
    count_binds = sum(1 for l in output_lines if l.startswith("INSERT") and "screen_metrics" in l)
    count_snaps = sum(1 for l in output_lines if l.startswith("INSERT") and "metric_snapshots" in l)
    count_settings = sum(1 for l in output_lines if l.startswith("INSERT") and "settings" in l)
    count_grants = sum(1 for l in output_lines if l.startswith("INSERT") and "workspace_grants" in l)

    print(f"Exported {count_defs} definitions, {count_binds} bindings, {count_snaps} snapshots, {count_settings} settings, {count_grants} grants -> db/metrics_backup.sql")


if __name__ == "__main__":
    main()
